### ISSUE TITLE
DataTransferObjects

### ISSUE THREAD

**Issue by kevariable** [KoalaFacade/diamond-of-ddd#2]
DTO abstract class looks to much function unesserary, some cases in PHP > 8.0 version its really enough for maintain the DTO e.g spatie/data-transfer-object has been archived. My proposal to improve `resolve(array $data)` to use central method of `resolveFrom(mixed $abstract)`.

When deadling with many to split the dirty data into structure we usually will working with Request, Model and etc. Its will be nice to have one central method to handled those things e.g when catch up the request

```php
public static function resolveFrom(mixed $abstract): static
{
        if (Arr::accessible($abstract)) {
            return static::resolve($abstract);
        }

       // handle another consolidate conditional

        return throw new \RuntimeException; // this can be default value return or exception to make it consistent
}

public static function resolve(array $data): static
{
      ... array key-in
}
```

some client-side

```php
CustomerData::resolveFrom($request)
```

and another proposal its to cleaning the DataTransferObject that only use nessecary things

**Comment by pemudakoding** [comment]
probably you see some method like excluded and get excluded method. if you realise you might work with a bunch of properties,
it's quite take our time to redefine in eloquent create() or update(). so those method will resolve your properties with your database column naming so you no need to write the attributes manually. what do you think? do u have better idea to implement it? 

hope you able to produce `resolveFrom(mixed $abstract)` to our repo, wanna see how you resolve incoming data :)

**Comment by kevariable** [comment]
Hi, i usually will handle by myself for persistent into database, i frequently to use `updateOrCreate` method and probably you do. Whats if those things to keep clean we can Separate of Concerns into Traits so:

```php
Domain\Shared\Foundation\DataTransferObject.php

Domain\Shared\Foundation\DataTransferObject\HasAttributes.php
```

in some clients when its truely used

```php
class CustomerData extends DataTransferObject
{
       use DataTransferObject\HasAttributes;
}
```

**Comment by kevariable** [comment]
perhaps we might dont need the DataTransferObject base class, we might only need Contracts

**Comment by kevariable** [comment]
i am truely love whats you are doing but we need to consider the principle of [YAGNI](https://martinfowler.com/bliki/Yagni.html) and perhaps the `readonly` class that introduced in PHP 8.2 will make it cleaner

**Comment by pemudakoding** [comment]
alright got ur point, so to hold the YAGNI principle, we can provide it as trait, so it's like composition, they can use or not it depends on the user.

**Comment by kevariable** [comment]
yep flexible as possible, they ask we give, the dont ask we dont give. I will prepare to handle this later and the docs of example the proposal. Cheers 🍻

**Comment by kevariable** [comment]
#3 was implemented
